name: Sleep Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 3
      - run: sleep 2
      - run: sleep 5
      - name: Sleep 4 seconds
        run: sleep 4
