on:
   workflow_dispatch:
jobs:
   jobs1:
      runs-on: ubuntu-latest
      steps:
        - run: sleep 3
        - run: sleep 2
        - run: sleep 5
        - name: sleep4sec
          run: sleep 4